[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server"
  status = 200
