[build]
base = "."               # Root folder where your frontend code is
publish = "build"        # This is the folder generated after `npm run build`
command = "npm run build" # Default React build command

[functions]
directory = "netlify/functions"  # Folder for backend (serverless functions)
